### ISSUE TITLE
Сложности при работе с расширением

### ISSUE THREAD

**Issue by Kristalliya** [Kristalliya/1C-VKR#11]
1) Как запускать расширение, чтобы оно работало при запуске конфигурации
2) Как правильно запускать в расширении формы, работать с обработчиком
3) Как правильно в расширение добавить отчет и он показывался при запуске конфигуратора
4) Как правильно в расширение добавить новую форму и она показывалась правильно при запуске конфигуратора

**Comment by faridlesosibirsk** [comment]
нашел статью http://v8.1c.ru/o7/201410ext/
если статья не поможет - что вы читаете про механизм расширений в 1С?

**Comment by Kristalliya** [comment]
Расширение. Полезная информация
Расширения от 30.10.2014 http://v8.1c.ru/o7/201410ext/index.htm
Расширения модулей http://v8.1c.ru/o7/201603module/index.htm
Добавление собственных ролей http://v8.1c.ru/o7/201603ext/index.htm
Расширения конфигурации. Полезные советы для разработки Код, ХранилищеНастроек и др https://infostart.ru/public/442003/#Pamyatka
Расширения конфигураций в 1С: основные понятия и методы http://blog.it-terminal.ru/programmirovanie-1s/1s-rasshirenie-konfiguracii.html
Расширения конфигураций – как добавить функционал в типовую конфигурацию, не снимая с поддержки (20 минут видео)
https://xn----1-bedvffifm4g.xn--p1ai/news/2016-07-27-how-to-use-extensions/

Доработка прикладных решений с помощью расширений конфигурации https://1cfresh.com/articles/so_confext

расширения и недоступные реквизиты http://www.cyberforum.ru/1c-custom/thread2123888.html
«Расширения» конфигураций 1С:Предприятия https://is1c.ru/about/pc/news/rasshireniya-konfiguratsiy-1s-predpriyatiya/
Как работать с расширением конфигурации в 1С. Практическое использование механизма расширений https://www.koderline.ru/expert/instruktsii/article-kak-rabotat-s-rasshireniem-konfiguratsii-v-1s-prakticheskoe-ispolzovanie-mekhanizma-rasshireniy/

**Comment by Kristalliya** [comment]
Возможная причина неработоспособности расширения: В базовых версиях работа с расширениями не поддерживается

**Comment by Kristalliya** [comment]
Возможная причина неработоспособности расширения: В базовых версиях работа с расширениями не поддерживается
