### ISSUE TITLE
Схема данных

### ISSUE THREAD

**Issue by faridlesosibirsk** [Kristalliya/1C-VKR#15]
https://wonderland.v8.1c.ru/blog/skhema-dannykh/

**Comment by Kristalliya** [comment]
Установка 1c_enterprise_development_tools_distr_1.9.3_53_windows_x86_64
1C:Enterprise Development Tools (EDT) -1CEDT (1.9.3+53)
Проблема:
Версия 8.3.10.2252 не поддерживается. EDT поддерживает платформы версии 8.3.10 начиная только с номера сборки 2428.
Версия 8.3.13 не поддерживается

**Comment by Kristalliya** [comment]
[1C Предприятие 8.3.10.2650](http://vtorrente.pp.ua/load/soft/operacionnye_sistemy/1s_predprijatie_8_3_10_2017/70-1-0-5240)

**Comment by Kristalliya** [comment]
Работает только с регистрами и на основе регистра строит схему данных. 
У отчета Дни рождения Сотрудников нет сущностей, указывающих на на него.
