### ISSUE TITLE
для непрерывного  анализа и измерения качества кода.

### ISSUE THREAD

**Issue by faridlesosibirsk** [Kristalliya/1C-VKR#20]
[SonarQube](https://ru.wikipedia.org/wiki/SonarQube)

**Comment by faridlesosibirsk** [comment]
[Install the SonarScanner](https://docs.sonarqube.org/display/SCAN/Install+the+SonarScanner+for+MSBuild)

**Comment by faridlesosibirsk** [comment]
https://silverbulleters.org/sonarqube

**Comment by faridlesosibirsk** [comment]
http://oscript.io/downloads

**Comment by faridlesosibirsk** [comment]
`StartSonar.bat`

```
C:\Users\***\Documents\kamin\kdr30Demo>C:\Users\****\Downloads\sonar-scanner-
3.2.0.1227\bin\sonar-scanner -Dsonar.projectKey=1c -Dsonar.sources=. -Dsonar.hos
t.url=http://127.0.0.1:9000 -Dsonar.login=c14c432ea4deae0******6e984a01089e6d
```

**Comment by Kristalliya** [comment]
[Visual Studio Code – редактор кода для Linux, OS X и Windows](https://habr.com/company/microsoft/blog/262523/)

**Comment by Kristalliya** [comment]
Установка 1c_enterprise_development_tools_distr_1.9.3_53_windows_x86_64
1C:Enterprise Development Tools (EDT) -1CEDT (1.9.3+53)
Проблема:
Версия 8.3.10.2252 не поддерживается. EDT поддерживает платформы версии 8.3.10 начиная только с номера сборки 2428.
Версия 8.3.13 не поддерживается
