### ISSUE TITLE
Сделать выгрузку в GIT

### ISSUE THREAD

**Issue by faridlesosibirsk** [Kristalliya/1C-VKR#21]
[Использование GIT для разработки в 1С ](http://prosto1s.ru/index.php/70-git-1)

**Comment by Kristalliya** [comment]
Команды для начала работы:
cd 'E:\1C_VKR'
git clone https://github.com/Kristalliya/1C-VKR

Используемые команды для создания:
echo "# 1C-P" >> README.md
git init
git add README.md
git commit -m "first commit"
git remote add origin https://github.com/Kristalliya/1C-VKR.git
git push -u origin master

Команды для загрузки файлов:
git add .
git status
git commit -m 'configurator дата(13.12.18) время(9:36)' или git commit -m 'rasshirenie дата(13.12.18) время(9:36)'
git log
git push origin master

**Comment by Kristalliya** [comment]
Расширение для конфигуратора 1С-Предприятие Кадровый учет 3.0 (демо)
